export const pays = [
     { nom: "Afghanistan", drapeau: "🇦🇫", couleur: "#002F6C" },
    { nom: "South Africa", drapeau: "🇿🇦", couleur: "#007847" },
    { nom: "Albania", drapeau: "🇦🇱", couleur: "#E41E20" },
    { nom: "Algeria", drapeau: "🇩🇿", couleur: "#006233" },
    { nom: "Germany", drapeau: "🇩🇪", couleur: "#000000" },
    { nom: "Andorra", drapeau: "🇦🇩", couleur: "#D61024" },
    { nom: "Angola", drapeau: "🇦🇴", couleur: "#FF0000" },
    { nom: "Saudi Arabia", drapeau: "🇸🇦", couleur: "#006C35" },
    { nom: "Argentina", drapeau: "🇦🇷", couleur: "#75AADB" },
    { nom: "Armenia", drapeau: "🇦🇲", couleur: "#D90012" },
    { nom: "Australia", drapeau: "🇦🇺", couleur: "#002868" },
    { nom: "Austria", drapeau: "🇦🇹", couleur: "#EF3340" },
    { nom: "Azerbaijan", drapeau: "🇦🇿", couleur: "#0094C8" },
    { nom: "Bahamas", drapeau: "🇧🇸", couleur: "#00778B" },
    { nom: "Bahrain", drapeau: "🇧🇭", couleur: "#D71A28" },
    { nom: "Bangladesh", drapeau: "🇧🇩", couleur: "#006A4E" },
    { nom: "Belgium", drapeau: "🇧🇪", couleur: "#FAE042" },
    { nom: "Benin", drapeau: "🇧🇯", couleur: "#FCD116" },
    { nom: "Bhutan", drapeau: "🇧🇹", couleur: "#FFCC00" },
    { nom: "Belarus", drapeau: "🇧🇾", couleur: "#D32F2F" },
    { nom: "Bolivia", drapeau: "🇧🇴", couleur: "#DA291C" },
    { nom: "Botswana", drapeau: "🇧🇼", couleur: "#6DA9D2" },
    { nom: "Brazil", drapeau: "🇧🇷", couleur: "#009739" },
    { nom: "Bulgaria", drapeau: "🇧🇬", couleur: "#00966E" },
    { nom: "Burkina Faso", drapeau: "🇧🇫", couleur: "#EF3340" },
    { nom: "Burundi", drapeau: "🇧🇮", couleur: "#118600" },
    { nom: "Cameroon", drapeau: "🇨🇲", couleur: "#007A5E" },
    { nom: "Canada", drapeau: "🇨🇦", couleur: "#D52B1E" },
    { nom: "Cape Verde", drapeau: "🇨🇻", couleur: "#0033A0" },
    { nom: "Chile", drapeau: "🇨🇱", couleur: "#D52B1E" },
    { nom: "China", drapeau: "🇨🇳", couleur: "#DE2910" },
    { nom: "Colombia", drapeau: "🇨🇴", couleur: "#FFD700" },
    { nom: "Comoros", drapeau: "🇰🇲", couleur: "#FFD700" },
    { nom: "Congo (Brazzaville)", drapeau: "🇨🇬", couleur: "#009543" },
    { nom: "Congo (Kinshasa)", drapeau: "🇨🇩", couleur: "#FCD116" },
    { nom: "North Korea", drapeau: "🇰🇵", couleur: "#C60C30" },
    { nom: "South Korea", drapeau: "🇰🇷", couleur: "#003478" },
    { nom: "Costa Rica", drapeau: "🇨🇷", couleur: "#002B7F" },
    { nom: "Ivory Coast", drapeau: "🇨🇮", couleur: "#F77F00" },
    { nom: "Croatia", drapeau: "🇭🇷", couleur: "#171796" },
    { nom: "Cuba", drapeau: "🇨🇺", couleur: "#0055A4" },
    { nom: "Denmark", drapeau: "🇩🇰", couleur: "#C8102E" },
    { nom: "Djibouti", drapeau: "🇩🇯", couleur: "#0095B6" },
    { nom: "Egypt", drapeau: "🇪🇬", couleur: "#C8102E" },
    { nom: "United Arab Emirates", drapeau: "🇦🇪", couleur: "#00732F" },
    { nom: "Ecuador", drapeau: "🇪🇨", couleur: "#FFD700" },
    { nom: "Spain", drapeau: "🇪🇸", couleur: "#FFCC00" },
    { nom: "Estonia", drapeau: "🇪🇪", couleur: "#0072CE" },
    { nom: "United States", drapeau: "🇺🇸", couleur: "#B22234" },
    { nom: "Ethiopia", drapeau: "🇪🇹", couleur: "#008000" },
    { nom: "Fiji", drapeau: "🇫🇯", couleur: "#5BC4E8" },
    { nom: "France", drapeau: "🇫🇷", couleur: "#0055A4" },
    { nom: "Gabon", drapeau: "🇬🇦", couleur: "#009B77" },
    { nom: "Gambia", drapeau: "🇬🇲", couleur: "#008F7B" },
    { nom: "Georgia", drapeau: "🇬🇪", couleur: "#C8102E" },
    { nom: "Ghana", drapeau: "🇬🇭", couleur: "#F00A12" },
    { nom: "Greece", drapeau: "🇬🇷", couleur: "#0D5E8C" },
    { nom: "Grenada", drapeau: "🇬🇩", couleur: "#F03C31" },
    { nom: "Guatemala", drapeau: "🇬🇹", couleur: "#009639" },
    { nom: "Guinea", drapeau: "🇬🇳", couleur: "#FCD116" },
    { nom: "Guinea-Bissau", drapeau: "🇬🇼", couleur: "#E30B17" },
    { nom: "Guyana", drapeau: "🇬🇾", couleur: "#009739" },
    { nom: "Haiti", drapeau: "🇭🇹", couleur: "#0D47A1" },
    { nom: "Honduras", drapeau: "🇭🇳", couleur: "#0033A0" },
    { nom: "Hungary", drapeau: "🇭🇺", couleur: "#C8102E" },
    { nom: "India", drapeau: "🇮🇳", couleur: "#FF9933" },
    { nom: "Indonesia", drapeau: "🇮🇩", couleur: "#D71A28" },
    { nom: "Iraq", drapeau: "🇮🇶", couleur: "#006747" },
    { nom: "Ireland", drapeau: "🇮🇪", couleur: "#009B77" },
    { nom: "Israel", drapeau: "🇮🇱", couleur: "#0038A8" },
    { nom: "Italy", drapeau: "🇮🇹", couleur: "#008C45" },
    { nom: "Jamaica", drapeau: "🇯🇲", couleur: "#F8B500" },
    { nom: "Japan", drapeau: "🇯🇵", couleur: "#BC002D" },
    { nom: "Jordan", drapeau: "🇯🇴", couleur: "#F00A12" },
    { nom: "Kazakhstan", drapeau: "🇰🇿", couleur: "#00A9E0" },
    { nom: "Kenya", drapeau: "🇰🇪", couleur: "#FF0000" },
    { nom: "Kyrgyzstan", drapeau: "🇰🇬", couleur: "#E10000" },
    { nom: "Kiribati", drapeau: "🇰🇮", couleur: "#FFCB00" },
    { nom: "Kuwait", drapeau: "🇰🇼", couleur: "#F00A12" },
    { nom: "Laos", drapeau: "🇱🇦", couleur: "#0038A8" },
    { nom: "Lesotho", drapeau: "🇱🇸", couleur: "#000000" },
    { nom: "Latvia", drapeau: "🇱🇻", couleur: "#9E0031" },
    { nom: "Lebanon", drapeau: "🇱🇧", couleur: "#D71A28" },
    { nom: "Liberia", drapeau: "🇱🇸", couleur: "#009639" },
    { nom: "Libya", drapeau: "🇱🇾", couleur: "#009E49" },
    { nom: "Liechtenstein", drapeau: "🇱🇮", couleur: "#1E47A1" },
    { nom: "Lithuania", drapeau: "🇱🇹", couleur: "#FCD116" },
    { nom: "Luxembourg", drapeau: "🇱🇺", couleur: "#F00A12" },
    { nom: "North Macedonia", drapeau: "🇲🇰", couleur: "#E50000" },
    { nom: "Madagascar", drapeau: "🇲🇬", couleur: "#007847" },
    { nom: "Malaysia", drapeau: "🇲🇾", couleur: "#F00A12" },
    { nom: "Malawi", drapeau: "🇲🇼", couleur: "#D71A28" },
    { nom: "Maldives", drapeau: "🇲🇻", couleur: "#008C45" },
    { nom: "Mali", drapeau: "🇲🇱", couleur: "#F9A825" },
    { nom: "Malta", drapeau: "🇲🇹", couleur: "#00A2E8" },
    { nom: "Marshall Islands", drapeau: "🇲🇭", couleur: "#0072BB" },
    { nom: "Mauritania", drapeau: "🇲🇷", couleur: "#E4002B" },
    { nom: "Mauritius", drapeau: "🇲🇺", couleur: "#009C48" },
    { nom: "Mexico", drapeau: "🇲🇽", couleur: "#006F2D" },
    { nom: "Micronesia", drapeau: "🇫🇲", couleur: "#0071C5" },
    { nom: "Moldova", drapeau: "🇲🇩", couleur: "#009B77" },
    { nom: "Monaco", drapeau: "🇲🇨", couleur: "#F00A12" },
    { nom: "Mongolia", drapeau: "🇲🇳", couleur: "#F00A12" },
    { nom: "Montenegro", drapeau: "🇲🇪", couleur: "#FF1F30" },
    { nom: "Morocco", drapeau: "🇲🇦", couleur: "#007A3D" },
    { nom: "Mozambique", drapeau: "🇲🇿", couleur: "#F00A12" },
    { nom: "Myanmar", drapeau: "🇲🇲", couleur: "#FFD700" },
    { nom: "Namibia", drapeau: "🇳🇦", couleur: "#0A75A3" },
    { nom: "Nauru", drapeau: "🇳🇷", couleur: "#0067B9" },
    { nom: "Nepal", drapeau: "🇳🇵", couleur: "#E4002B" },
    { nom: "Netherlands", drapeau: "🇳🇱", couleur: "#21468B" },
    { nom: "New Zealand", drapeau: "🇳🇿", couleur: "#00205B" },
    { nom: "Nicaragua", drapeau: "🇳🇮", couleur: "#006747" },
    { nom: "Niger", drapeau: "🇳🇪", couleur: "#F90" },
    { nom: "Nigeria", drapeau: "🇳🇬", couleur: "#008751" },
    { nom: "Norway", drapeau: "🇳🇴", couleur: "#BA0C2F" },
    { nom: "Oman", drapeau: "🇴🇲", couleur: "#9E1B32" },
    { nom: "Pakistan", drapeau: "🇵🇰", couleur: "#006B3F" },
    { nom: "Palau", drapeau: "🇵🇼", couleur: "#007C92" },
    { nom: "Panama", drapeau: "🇵🇦", couleur: "#F00A12" },
    { nom: "Papua New Guinea", drapeau: "🇵🇬", couleur: "#F00A12" },
    { nom: "Paraguay", drapeau: "🇵🇾", couleur: "#F00A12" },
    { nom: "Peru", drapeau: "🇵🇪", couleur: "#D52B1E" },
    { nom: "Philippines", drapeau: "🇵🇭", couleur: "#003478" },
    { nom: "Poland", drapeau: "🇵🇱", couleur: "#D52B1E" },
    { nom: "Portugal", drapeau: "🇵🇹", couleur: "#D52B1E" },
    { nom: "Qatar", drapeau: "🇶🇦", couleur: "#9E1B32" },
    { nom: "Romania", drapeau: "🇷🇴", couleur: "#00219C" },
    { nom: "Russia", drapeau: "🇷🇺", couleur: "#0000FF" },
    { nom: "Rwanda", drapeau: "🇷🇼", couleur: "#009639" },
    { nom: "Saint Kitts and Nevis", drapeau: "🇰🇳", couleur: "#F0C100" },
    { nom: "Saint Lucia", drapeau: "🇱🇨", couleur: "#0053A0" },
    { nom: "Saint Vincent and the Grenadines", drapeau: "🇻🇨", couleur: "#F0C100" },
    { nom: "Samoa", drapeau: "🇼🇸", couleur: "#002868" },
    { nom: "San Marino", drapeau: "🇸🇲", couleur: "#006B3F" },
    { nom: "Sao Tome and Principe", drapeau: "🇸🇹", couleur: "#F00A12" },
    { nom: "Saudi Arabia", drapeau: "🇸🇦", couleur: "#006C35" },
    { nom: "Senegal", drapeau: "🇸🇳", couleur: "#008B3D" },
    { nom: "Serbia", drapeau: "🇷🇸", couleur: "#0D5E8C" },
    { nom: "Seychelles", drapeau: "🇸🇨", couleur: "#F7B500" },
    { nom: "Sierra Leone", drapeau: "🇸🇱", couleur: "#009739" },
    { nom: "Singapore", drapeau: "🇸🇬", couleur: "#D71A28" },
    { nom: "Slovakia", drapeau: "🇸🇰", couleur: "#0A4C84" },
    { nom: "Slovenia", drapeau: "🇸🇮", couleur: "#0C2C84" },
    { nom: "Solomon Islands", drapeau: "🇸🇧", couleur: "#E34A33" },
    { nom: "Somalia", drapeau: "🇸🇴", couleur: "#00A9E0" },
    { nom: "South Africa", drapeau: "🇿🇦", couleur: "#006747" },
    { nom: "South Sudan", drapeau: "🇸🇸", couleur: "#007A5E" },
    { nom: "Spain", drapeau: "🇪🇸", couleur: "#FFCC00" },
    { nom: "Sri Lanka", drapeau: "🇱🇰", couleur: "#009739" },
    { nom: "Sudan", drapeau: "🇸🇩", couleur: "#D71A28" },
    { nom: "Surinom", drapeau: "🇸🇷", couleur: "#FF0000" },
    { nom: "Sweden", drapeau: "🇸🇪", couleur: "#006AA7" },
    { nom: "Switzerland", drapeau: "🇨🇭", couleur: "#E30B17" },
    { nom: "Syria", drapeau: "🇸🇾", couleur: "#007A3D" },
    { nom: "Taiwan", drapeau: "🇹🇼", couleur: "#007D3C" },
    { nom: "Tajikistan", drapeau: "🇹🇯", couleur: "#9E1B32" },
    { nom: "Tanzania", drapeau: "🇹🇿", couleur: "#FFB000" },
    { nom: "Thailand", drapeau: "🇹🇭", couleur: "#1C2D56" },
    { nom: "Timor-Leste", drapeau: "🇹🇱", couleur: "#F00A12" },
    { nom: "Togo", drapeau: "🇹🇬", couleur: "#005C56" },
    { nom: "Trinidad and Tobago", drapeau: "🇹🇹", couleur: "#F00A12" },
    { nom: "Tunisia", drapeau: "🇹🇳", couleur: "#E4002B" },
    { nom: "Turkey", drapeau: "🇹🇷", couleur: "#E30B17" },
    { nom: "Turkmenistan", drapeau: "🇹🇲", couleur: "#00A859" },
    { nom: "Tuvalu", drapeau: "🇹🇻", couleur: "#0093D4" },
    { nom: "Uganda", drapeau: "🇺🇬", couleur: "#F00A12" },
    { nom: "Ukraine", drapeau: "🇺🇦", couleur: "#005BBB" },
    { nom: "United Kingdom", drapeau: "🇬🇧", couleur: "#00247D" },
    { nom: "United States of America", drapeau: "🇺🇸", couleur: "#B22234" },
    { nom: "United Kingdom of Great Britain and Northern Ireland", drapeau: "🇬🇧", couleur: "#00247D" },
    { nom: "United States", drapeau: "🇺🇸", couleur: "#B22234" },
    { nom: "Uruguay", drapeau: "🇺🇾", couleur: "#FFD700" },
    { nom: "Uzbekistan", drapeau: "🇺🇿", couleur: "#009D4D" },
    { nom: "Vanuatu", drapeau: "🇻🇺", couleur: "#F80E0E" },
    { nom: "Vatican City", drapeau: "🇻🇦", couleur: "#FCD116" },
    { nom: "Venezuela", drapeau: "🇻🇪", couleur: "#F1A900" },
    { nom: "Vietnam", drapeau: "🇻🇳", couleur: "#F00A12" },
    { nom: "Yemen", drapeau: "🇾🇪", couleur: "#FF0000" },
    { nom: "Zambia", drapeau: "🇿🇲", couleur: "#009739" },
    { nom: "Zimbabwe", drapeau: "🇿🇼", couleur: "#E30B17" },
    { nom: "Afghanistan", drapeau: "🇦🇫", couleur: "#002F6C" },
    { nom: "Afrique du Sud", drapeau: "🇿🇦", couleur: "#007847" },
    { nom: "Albanie", drapeau: "🇦🇱", couleur: "#E41E20" },
    { nom: "Algérie", drapeau: "🇩🇿", couleur: "#006233" },
    { nom: "Allemagne", drapeau: "🇩🇪", couleur: "#000000" },
    { nom: "Andorre", drapeau: "🇦🇩", couleur: "#D61024" },
    { nom: "Angola", drapeau: "🇦🇴", couleur: "#FF0000" },
    { nom: "Arabie Saoudite", drapeau: "🇸🇦", couleur: "#006C35" },
    { nom: "Argentine", drapeau: "🇦🇷", couleur: "#75AADB" },
    { nom: "Arménie", drapeau: "🇦🇲", couleur: "#D90012" },
    { nom: "Australie", drapeau: "🇦🇺", couleur: "#002868" },
    { nom: "Autriche", drapeau: "🇦🇹", couleur: "#EF3340" },
    { nom: "Azerbaïdjan", drapeau: "🇦🇿", couleur: "#0094C8" },
    { nom: "Bahamas", drapeau: "🇧🇸", couleur: "#00778B" },
    { nom: "Bahreïn", drapeau: "🇧🇭", couleur: "#D71A28" },
    { nom: "Bangladesh", drapeau: "🇧🇩", couleur: "#006A4E" },
    { nom: "Belgique", drapeau: "🇧🇪", couleur: "#FAE042" },
    { nom: "Bénin", drapeau: "🇧🇯", couleur: "#FCD116" },
    { nom: "Bhoutan", drapeau: "🇧🇹", couleur: "#FFCC00" },
    { nom: "Biélorussie", drapeau: "🇧🇾", couleur: "#D32F2F" },
    { nom: "Bolivie", drapeau: "🇧🇴", couleur: "#DA291C" },
    { nom: "Botswana", drapeau: "🇧🇼", couleur: "#6DA9D2" },
    { nom: "Brésil", drapeau: "🇧🇷", couleur: "#009739" },
    { nom: "Bulgarie", drapeau: "🇧🇬", couleur: "#00966E" },
    { nom: "Burkina Faso", drapeau: "🇧🇫", couleur: "#EF3340" },
    { nom: "Burundi", drapeau: "🇧🇮", couleur: "#118600" },
    { nom: "Cameroun", drapeau: "🇨🇲", couleur: "#007A5E" },
    { nom: "Canada", drapeau: "🇨🇦", couleur: "#D52B1E" },
    { nom: "Cap-Vert", drapeau: "🇨🇻", couleur: "#0033A0" },
    { nom: "Chili", drapeau: "🇨🇱", couleur: "#D52B1E" },
    { nom: "Chine", drapeau: "🇨🇳", couleur: "#DE2910" },
    { nom: "Colombie", drapeau: "🇨🇴", couleur: "#FFD700" },
    { nom: "Comores", drapeau: "🇰🇲", couleur: "#FFD700" },
    { nom: "Congo (Brazzaville)", drapeau: "🇨🇬", couleur: "#009543" },
    { nom: "Congo (Kinshasa)", drapeau: "🇨🇩", couleur: "#FCD116" },
    { nom: "Corée du Nord", drapeau: "🇰🇵", couleur: "#C60C30" },
    { nom: "Corée du Sud", drapeau: "🇰🇷", couleur: "#003478" },
    { nom: "Costa Rica", drapeau: "🇨🇷", couleur: "#002B7F" },
    { nom: "Côte d'Ivoire", drapeau: "🇨🇮", couleur: "#F77F00" },
    { nom: "Croatie", drapeau: "🇭🇷", couleur: "#171796" },
    { nom: "Cuba", drapeau: "🇨🇺", couleur: "#0055A4" },
    { nom: "Danemark", drapeau: "🇩🇰", couleur: "#C8102E" },
    { nom: "Djibouti", drapeau: "🇩🇯", couleur: "#0095B6" },
    { nom: "Égypte", drapeau: "🇪🇬", couleur: "#C8102E" },
    { nom: "Émirats Arabes Unis", drapeau: "🇦🇪", couleur: "#00732F" },
    { nom: "Équateur", drapeau: "🇪🇨", couleur: "#FFD700" },
    { nom: "Espagne", drapeau: "🇪🇸", couleur: "#FFCC00" },
    { nom: "Estonie", drapeau: "🇪🇪", couleur: "#0072CE" },
    { nom: "États-Unis", drapeau: "🇺🇸", couleur: "#B22234" },
    { nom: "Éthiopie", drapeau: "🇪🇹", couleur: "#008000" },
    { nom: "Fidji", drapeau: "🇫🇯", couleur: "#5BC4E8" },
    { nom: "France", drapeau: "🇫🇷", couleur: "#0055A4" },
    { nom: "Gabon", drapeau: "🇬🇦", couleur: "#009B77" },
    { nom: "Gambie", drapeau: "🇬🇲", couleur: "#008F7B" },
    { nom: "Géorgie", drapeau: "🇬🇪", couleur: "#C8102E" },
    { nom: "Ghana", drapeau: "🇬🇭", couleur: "#F00A12" },
    { nom: "Grèce", drapeau: "🇬🇷", couleur: "#0D5E8C" },
    { nom: "Grenade", drapeau: "🇬🇩", couleur: "#F03C31" },
    { nom: "Guatemala", drapeau: "🇬🇹", couleur: "#009639" },
    { nom: "Guinée", drapeau: "🇬🇳", couleur: "#FCD116" },
    { nom: "Guinée-Bissau", drapeau: "🇬🇼", couleur: "#E30B17" },
    { nom: "Guyana", drapeau: "🇬🇾", couleur: "#009739" },
    { nom: "Haïti", drapeau: "🇭🇹", couleur: "#0D47A1" },
    { nom: "Honduras", drapeau: "🇭🇳", couleur: "#0033A0" },
    { nom: "Hongrie", drapeau: "🇭🇺", couleur: "#C8102E" },
    { nom: "Inde", drapeau: "🇮🇳", couleur: "#FF9933" },
    { nom: "Indonésie", drapeau: "🇮🇩", couleur: "#D71A28" },
    { nom: "Irak", drapeau: "🇮🇶", couleur: "#006747" },
    { nom: "Irlande", drapeau: "🇮🇪", couleur: "#009B77" },
    { nom: "Israël", drapeau: "🇮🇱", couleur: "#0038A8" },
    { nom: "Italie", drapeau: "🇮🇹", couleur: "#008C45" },
    { nom: "Jamaïque", drapeau: "🇯🇲", couleur: "#F8B500" },
    { nom: "Japon", drapeau: "🇯🇵", couleur: "#BC002D" },
    { nom: "Jordanie", drapeau: "🇯🇴", couleur: "#F00A12" },
    { nom: "Kazakhstan", drapeau: "🇰🇿", couleur: "#00A9E0" },
    { nom: "Kenya", drapeau: "🇰🇪", couleur: "#FF0000" },
    { nom: "Kirghizistan", drapeau: "🇰🇬", couleur: "#E10000" },
    { nom: "Kiribati", drapeau: "🇰🇮", couleur: "#FFCB00" },
    { nom: "Koweït", drapeau: "🇰🇼", couleur: "#F00A12" },
    { nom: "Laos", drapeau: "🇱🇦", couleur: "#0038A8" },
    { nom: "Lesotho", drapeau: "🇱🇸", couleur: "#000000" },
    { nom: "Lettonie", drapeau: "🇱🇻", couleur: "#9E0031" },
    { nom: "Liban", drapeau: "🇱🇧", couleur: "#D71A28" },
    { nom: "Liberia", drapeau: "🇱🇸", couleur: "#009639" },
    { nom: "Libye", drapeau: "🇱🇾", couleur: "#009E49" },
    { nom: "Liechtenstein", drapeau: "🇱🇮", couleur: "#1E47A1" },
    { nom: "Lituanie", drapeau: "🇱🇹", couleur: "#FCD116" },
    { nom: "Luxembourg", drapeau: "🇱🇺", couleur: "#F00A12" },
    { nom: "Macédoine", drapeau: "🇲🇰", couleur: "#E50000" },
    { nom: "Madagascar", drapeau: "🇲🇬", couleur: "#007847" },
    { nom: "Malaisie", drapeau: "🇲🇾", couleur: "#F00A12" },
    { nom: "Malawi", drapeau: "🇲🇼", couleur: "#D71A28" },
    { nom: "Maldives", drapeau: "🇲🇻", couleur: "#E0D819" },
    { nom: "Mali", drapeau: "🇲🇱", couleur: "#009E49" },
    { nom: "Malte", drapeau: "🇲🇹", couleur: "#F00A12" },
    { nom: "Maroc", drapeau: "🇲🇦", couleur: "#FF0000" },
    { nom: "Marshall", drapeau: "🇲🇭", couleur: "#1D4E89" },
    { nom: "Maurice", drapeau: "🇲🇺", couleur: "#E4002B" },
    { nom: "Mauritanie", drapeau: "🇲🇷", couleur: "#009639" },
    { nom: "Mexique", drapeau: "🇲🇽", couleur: "#006747" },
    { nom: "Micronésie", drapeau: "🇫🇲", couleur: "#48C6E4" },
    { nom: "Moldavie", drapeau: "🇲🇩", couleur: "#E10000" },
    { nom: "Monaco", drapeau: "🇲🇨", couleur: "#D71A28" },
    { nom: "Mongolie", drapeau: "🇲🇳", couleur: "#006AA7" },
    { nom: "Mozambique", drapeau: "🇲🇿", couleur: "#FF0000" },
    { nom: "Namibie", drapeau: "🇳🇦", couleur: "#009639" },
    { nom: "Nauru", drapeau: "🇳🇷", couleur: "#F9A100" },
    { nom: "Népal", drapeau: "🇳🇵", couleur: "#E10000" },
    { nom: "Nicaragua", drapeau: "🇳🇮", couleur: "#004E80" },
    { nom: "Niger", drapeau: "🇳🇬", couleur: "#FCD116" },
    { nom: "Nigeria", drapeau: "🇳🇬", couleur: "#008B4A" },
    { nom: "Niue", drapeau: "🇳🇺", couleur: "#0064A8" },
    { nom: "Norvège", drapeau: "🇳🇴", couleur: "#BA0C2F" },
    { nom: "Nouvelle-Zélande", drapeau: "🇳🇿", couleur: "#002B7F" },
    { nom: "Oman", drapeau: "🇴🇲", couleur: "#F00A12" },
    { nom: "Ouganda", drapeau: "🇺🇬", couleur: "#009E49" },
    { nom: "Pakistan", drapeau: "🇵🇰", couleur: "#006847" },
    { nom: "Palaos", drapeau: "🇵🇼", couleur: "#62B1B4" },
    { nom: "Panama", drapeau: "🇵🇦", couleur: "#0063B1" },
    { nom: "Papouasie-Nouvelle-Guinée", drapeau: "🇵🇬", couleur: "#E60012" },
    { nom: "Paraguay", drapeau: "🇵🇾", couleur: "#005BAC" },
    { nom: "Pays-Bas", drapeau: "🇳🇱", couleur: "#21468B" },
    { nom: "Pérou", drapeau: "🇵🇪", couleur: "#D91D29" },
    { nom: "Philippines", drapeau: "🇵🇭", couleur: "#0038A8" },
    { nom: "Pologne", drapeau: "🇵🇱", couleur: "#E4002B" },
    { nom: "Portugal", drapeau: "🇵🇹", couleur: "#006747" },
    { nom: "Qatar", drapeau: "🇶🇦", couleur: "#9E0022" },
    { nom: "République tchèque", drapeau: "🇨🇿", couleur: "#D52B1E" },
    { nom: "Roumanie", drapeau: "🇷🇴", couleur: "#FCD116" },
    { nom: "Royaume-Uni", drapeau: "🇬🇧", couleur: "#C8102E" },
    { nom: "Russie", drapeau: "🇷🇺", couleur: "#0000FF" },
    { nom: "Rwanda", drapeau: "🇷🇼", couleur: "#0A5F72" },
    { nom: "Saint-Christophe-et-Niévès", drapeau: "🇰🇳", couleur: "#FDBB30" },
    { nom: "Saint-Marin", drapeau: "🇸🇲", couleur: "#74B3D4" },
    { nom: "Saint-Vincent-et-les-Grenadines", drapeau: "🇻🇨", couleur: "#01A7D6" },
    { nom: "Sao Tomé-et-Principe", drapeau: "🇸🇹", couleur: "#3E8E41" },
    { nom: "Sénégal", drapeau: "🇸🇳", couleur: "#009639" },
    { nom: "Serbie", drapeau: "🇷🇸", couleur: "#D71A28" },
    { nom: "Seychelles", drapeau: "🇸🇨", couleur: "#FFD700" },
    { nom: "Sierra Leone", drapeau: "🇸🇱", couleur: "#18B2AA" },
    { nom: "Singapour", drapeau: "🇸🇬", couleur: "#E4002B" },
    { nom: "Slovaquie", drapeau: "🇸🇰", couleur: "#006B3F" },
    { nom: "Slovénie", drapeau: "🇸🇮", couleur: "#FFFFFF" },
    { nom: "Somalie", drapeau: "🇸🇴", couleur: "#009C9C" },
    { nom: "Soudan", drapeau: "🇸🇩", couleur: "#F00A12" },
    { nom: "Soudan du Sud", drapeau: "🇸🇸", couleur: "#1F6B3C" },
    { nom: "Sri Lanka", drapeau: "🇱🇰", couleur: "#F8B900" },
    { nom: "Suède", drapeau: "🇸🇪", couleur: "#006AA7" },
    { nom: "Suisse", drapeau: "🇨🇭", couleur: "#FF0000" },
    { nom: "Syrie", drapeau: "🇸🇾", couleur: "#D71A28" },
    { nom: "Tadjikistan", drapeau: "🇹🇯", couleur: "#F80B1D" },
    { nom: "Tanzanie", drapeau: "🇹🇿", couleur: "#FFB81C" },
    { nom: "Tchad", drapeau: "🇹🇩", couleur: "#009639" },
    { nom: "Thaïlande", drapeau: "🇹🇭", couleur: "#C8102E" },
    { nom: "Timor-Leste", drapeau: "🇹🇱", couleur: "#E40000" },
    { nom: "Togo", drapeau: "🇹🇬", couleur: "#009639" },
    { nom: "Tonga", drapeau: "🇹🇴", couleur: "#F5A5A1" },
    { nom: "Trinité-et-Tobago", drapeau: "🇹🇹", couleur: "#E4002B" },
    { nom: "Tunisie", drapeau: "🇹🇳", couleur: "#E60012" },
    { nom: "Turkménistan", drapeau: "🇹🇲", couleur: "#006747" },
    { nom: "Turquie", drapeau: "🇹🇷", couleur: "#E30B17" },
    { nom: "Tuvalu", drapeau: "🇹🇻", couleur: "#0089C2" },
    { nom: "Ukraine", drapeau: "🇺🇦", couleur: "#0066B1" },
    { nom: "Uruguay", drapeau: "🇺🇾", couleur: "#FFD700" },
    { nom: "United States of America", drapeau: "🇺🇸", couleur: "#B22234" },
    { nom: "United Kingdom of Great Britain and Northern Ireland", drapeau: "🇬🇧", couleur: "#00247D" },
    { nom: "Vanuatu", drapeau: "🇻🇺", couleur: "#00A14E" },
    { nom: "Vatican", drapeau: "🇻🇦", couleur: "#FFD700" },
    { nom: "Venezuela", drapeau: "🇻🇪", couleur: "#FCD116" },
    { nom: "Vietnam", drapeau: "🇻🇳", couleur: "#F00A12" },
    { nom: "Yémen", drapeau: "🇾🇪", couleur: "#D71A28" },
    { nom: "Zambie", drapeau: "🇿🇲", couleur: "#007847" },
    { nom: "Zimbabwe", drapeau: "🇿🇼", couleur: "#00A859" }
];

